---
swagger: "2.0"
type: object
example:
  user:
    userId: abc789
    username: markcrane
properties:
  user:
    type: object
    properties:
      userId:
        type: string
      username:
        type: string
